#pragma once

// Auto-generated from driver/ headers

#ifndef USB_DEVICE_ID_RAZER_OROCHI_2011
#define USB_DEVICE_ID_RAZER_OROCHI_2011 0x0013
#endif
#ifndef USB_DEVICE_ID_RAZER_NAGA
#define USB_DEVICE_ID_RAZER_NAGA 0x0015
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_3_5G
#define USB_DEVICE_ID_RAZER_DEATHADDER_3_5G 0x0016
#endif
#ifndef USB_DEVICE_ID_RAZER_NAGA_EPIC
#define USB_DEVICE_ID_RAZER_NAGA_EPIC 0x001F
#endif
#ifndef USB_DEVICE_ID_RAZER_ABYSSUS_1800
#define USB_DEVICE_ID_RAZER_ABYSSUS_1800 0x0020
#endif
#ifndef USB_DEVICE_ID_RAZER_MAMBA_2012_WIRED
#define USB_DEVICE_ID_RAZER_MAMBA_2012_WIRED 0x0024
#endif
#ifndef USB_DEVICE_ID_RAZER_MAMBA_2012_WIRELESS
#define USB_DEVICE_ID_RAZER_MAMBA_2012_WIRELESS 0x0025
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_3_5G_BLACK
#define USB_DEVICE_ID_RAZER_DEATHADDER_3_5G_BLACK 0x0029
#endif
#ifndef USB_DEVICE_ID_RAZER_NAGA_2012
#define USB_DEVICE_ID_RAZER_NAGA_2012 0x002E
#endif
#ifndef USB_DEVICE_ID_RAZER_IMPERATOR
#define USB_DEVICE_ID_RAZER_IMPERATOR 0x002F
#endif
#ifndef USB_DEVICE_ID_RAZER_OUROBOROS
#define USB_DEVICE_ID_RAZER_OUROBOROS 0x0032
#endif
#ifndef USB_DEVICE_ID_RAZER_TAIPAN
#define USB_DEVICE_ID_RAZER_TAIPAN 0x0034
#endif
#ifndef USB_DEVICE_ID_RAZER_NAGA_HEX_RED
#define USB_DEVICE_ID_RAZER_NAGA_HEX_RED 0x0036
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_2013
#define USB_DEVICE_ID_RAZER_DEATHADDER_2013 0x0037
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_1800
#define USB_DEVICE_ID_RAZER_DEATHADDER_1800 0x0038
#endif
#ifndef USB_DEVICE_ID_RAZER_OROCHI_2013
#define USB_DEVICE_ID_RAZER_OROCHI_2013 0x0039
#endif
#ifndef USB_DEVICE_ID_RAZER_NAGA_EPIC_CHROMA
#define USB_DEVICE_ID_RAZER_NAGA_EPIC_CHROMA 0x003E
#endif
#ifndef USB_DEVICE_ID_RAZER_NAGA_EPIC_CHROMA_DOCK
#define USB_DEVICE_ID_RAZER_NAGA_EPIC_CHROMA_DOCK 0x003F
#endif
#ifndef USB_DEVICE_ID_RAZER_NAGA_2014
#define USB_DEVICE_ID_RAZER_NAGA_2014 0x0040
#endif
#ifndef USB_DEVICE_ID_RAZER_NAGA_HEX
#define USB_DEVICE_ID_RAZER_NAGA_HEX 0x0041
#endif
#ifndef USB_DEVICE_ID_RAZER_ABYSSUS
#define USB_DEVICE_ID_RAZER_ABYSSUS 0x0042
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_CHROMA
#define USB_DEVICE_ID_RAZER_DEATHADDER_CHROMA 0x0043
#endif
#ifndef USB_DEVICE_ID_RAZER_MAMBA_WIRED
#define USB_DEVICE_ID_RAZER_MAMBA_WIRED 0x0044
#endif
#ifndef USB_DEVICE_ID_RAZER_MAMBA_WIRELESS
#define USB_DEVICE_ID_RAZER_MAMBA_WIRELESS 0x0045
#endif
#ifndef USB_DEVICE_ID_RAZER_MAMBA_TE_WIRED
#define USB_DEVICE_ID_RAZER_MAMBA_TE_WIRED 0x0046
#endif
#ifndef USB_DEVICE_ID_RAZER_OROCHI_CHROMA
#define USB_DEVICE_ID_RAZER_OROCHI_CHROMA 0x0048
#endif
#ifndef USB_DEVICE_ID_RAZER_DIAMONDBACK_CHROMA
#define USB_DEVICE_ID_RAZER_DIAMONDBACK_CHROMA 0x004C
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_2000
#define USB_DEVICE_ID_RAZER_DEATHADDER_2000 0x004F
#endif
#ifndef USB_DEVICE_ID_RAZER_NAGA_HEX_V2
#define USB_DEVICE_ID_RAZER_NAGA_HEX_V2 0x0050
#endif
#ifndef USB_DEVICE_ID_RAZER_NAGA_CHROMA
#define USB_DEVICE_ID_RAZER_NAGA_CHROMA 0x0053
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_3500
#define USB_DEVICE_ID_RAZER_DEATHADDER_3500 0x0054
#endif
#ifndef USB_DEVICE_ID_RAZER_LANCEHEAD_WIRED
#define USB_DEVICE_ID_RAZER_LANCEHEAD_WIRED 0x0059
#endif
#ifndef USB_DEVICE_ID_RAZER_LANCEHEAD_WIRELESS
#define USB_DEVICE_ID_RAZER_LANCEHEAD_WIRELESS 0x005A
#endif
#ifndef USB_DEVICE_ID_RAZER_ABYSSUS_V2
#define USB_DEVICE_ID_RAZER_ABYSSUS_V2 0x005B
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_ELITE
#define USB_DEVICE_ID_RAZER_DEATHADDER_ELITE 0x005C
#endif
#ifndef USB_DEVICE_ID_RAZER_ABYSSUS_2000
#define USB_DEVICE_ID_RAZER_ABYSSUS_2000 0x005E
#endif
#ifndef USB_DEVICE_ID_RAZER_LANCEHEAD_TE_WIRED
#define USB_DEVICE_ID_RAZER_LANCEHEAD_TE_WIRED 0x0060
#endif
#ifndef USB_DEVICE_ID_RAZER_ATHERIS_RECEIVER
#define USB_DEVICE_ID_RAZER_ATHERIS_RECEIVER 0x0062
#endif
#ifndef USB_DEVICE_ID_RAZER_BASILISK
#define USB_DEVICE_ID_RAZER_BASILISK 0x0064
#endif
#ifndef USB_DEVICE_ID_RAZER_BASILISK_ESSENTIAL
#define USB_DEVICE_ID_RAZER_BASILISK_ESSENTIAL 0x0065
#endif
#ifndef USB_DEVICE_ID_RAZER_NAGA_TRINITY
#define USB_DEVICE_ID_RAZER_NAGA_TRINITY 0x0067
#endif
#ifndef USB_DEVICE_ID_RAZER_ABYSSUS_ELITE_DVA_EDITION
#define USB_DEVICE_ID_RAZER_ABYSSUS_ELITE_DVA_EDITION 0x006A
#endif
#ifndef USB_DEVICE_ID_RAZER_ABYSSUS_ESSENTIAL
#define USB_DEVICE_ID_RAZER_ABYSSUS_ESSENTIAL 0x006B
#endif
#ifndef USB_DEVICE_ID_RAZER_MAMBA_ELITE
#define USB_DEVICE_ID_RAZER_MAMBA_ELITE 0x006C
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_ESSENTIAL
#define USB_DEVICE_ID_RAZER_DEATHADDER_ESSENTIAL 0x006E
#endif
#ifndef USB_DEVICE_ID_RAZER_LANCEHEAD_WIRELESS_RECEIVER
#define USB_DEVICE_ID_RAZER_LANCEHEAD_WIRELESS_RECEIVER 0x006F
#endif
#ifndef USB_DEVICE_ID_RAZER_LANCEHEAD_WIRELESS_WIRED
#define USB_DEVICE_ID_RAZER_LANCEHEAD_WIRELESS_WIRED 0x0070
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_ESSENTIAL_WHITE_EDITION
#define USB_DEVICE_ID_RAZER_DEATHADDER_ESSENTIAL_WHITE_EDITION 0x0071
#endif
#ifndef USB_DEVICE_ID_RAZER_MAMBA_WIRELESS_RECEIVER
#define USB_DEVICE_ID_RAZER_MAMBA_WIRELESS_RECEIVER 0x0072
#endif
#ifndef USB_DEVICE_ID_RAZER_MAMBA_WIRELESS_WIRED
#define USB_DEVICE_ID_RAZER_MAMBA_WIRELESS_WIRED 0x0073
#endif
#ifndef USB_DEVICE_ID_RAZER_PRO_CLICK_RECEIVER
#define USB_DEVICE_ID_RAZER_PRO_CLICK_RECEIVER 0x0077
#endif
#ifndef USB_DEVICE_ID_RAZER_VIPER
#define USB_DEVICE_ID_RAZER_VIPER 0x0078
#endif
#ifndef USB_DEVICE_ID_RAZER_VIPER_ULTIMATE_WIRED
#define USB_DEVICE_ID_RAZER_VIPER_ULTIMATE_WIRED 0x007A
#endif
#ifndef USB_DEVICE_ID_RAZER_VIPER_ULTIMATE_WIRELESS
#define USB_DEVICE_ID_RAZER_VIPER_ULTIMATE_WIRELESS 0x007B
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_V2_PRO_WIRED
#define USB_DEVICE_ID_RAZER_DEATHADDER_V2_PRO_WIRED 0x007C
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_V2_PRO_WIRELESS
#define USB_DEVICE_ID_RAZER_DEATHADDER_V2_PRO_WIRELESS 0x007D
#endif
#ifndef USB_DEVICE_ID_RAZER_PRO_CLICK_WIRED
#define USB_DEVICE_ID_RAZER_PRO_CLICK_WIRED 0x0080
#endif
#ifndef USB_DEVICE_ID_RAZER_BASILISK_X_HYPERSPEED
#define USB_DEVICE_ID_RAZER_BASILISK_X_HYPERSPEED 0x0083
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_V2
#define USB_DEVICE_ID_RAZER_DEATHADDER_V2 0x0084
#endif
#ifndef USB_DEVICE_ID_RAZER_BASILISK_V2
#define USB_DEVICE_ID_RAZER_BASILISK_V2 0x0085
#endif
#ifndef USB_DEVICE_ID_RAZER_BASILISK_ULTIMATE_WIRED
#define USB_DEVICE_ID_RAZER_BASILISK_ULTIMATE_WIRED 0x0086
#endif
#ifndef USB_DEVICE_ID_RAZER_BASILISK_ULTIMATE_RECEIVER
#define USB_DEVICE_ID_RAZER_BASILISK_ULTIMATE_RECEIVER 0x0088
#endif
#ifndef USB_DEVICE_ID_RAZER_VIPER_MINI
#define USB_DEVICE_ID_RAZER_VIPER_MINI 0x008A
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_V2_MINI
#define USB_DEVICE_ID_RAZER_DEATHADDER_V2_MINI 0x008C
#endif
#ifndef USB_DEVICE_ID_RAZER_NAGA_LEFT_HANDED_2020
#define USB_DEVICE_ID_RAZER_NAGA_LEFT_HANDED_2020 0x008D
#endif
#ifndef USB_DEVICE_ID_RAZER_NAGA_PRO_WIRED
#define USB_DEVICE_ID_RAZER_NAGA_PRO_WIRED 0x008F
#endif
#ifndef USB_DEVICE_ID_RAZER_NAGA_PRO_WIRELESS
#define USB_DEVICE_ID_RAZER_NAGA_PRO_WIRELESS 0x0090
#endif
#ifndef USB_DEVICE_ID_RAZER_VIPER_8K
#define USB_DEVICE_ID_RAZER_VIPER_8K 0x0091
#endif
#ifndef USB_DEVICE_ID_RAZER_OROCHI_V2_RECEIVER
#define USB_DEVICE_ID_RAZER_OROCHI_V2_RECEIVER 0x0094
#endif
#ifndef USB_DEVICE_ID_RAZER_OROCHI_V2_BLUETOOTH
#define USB_DEVICE_ID_RAZER_OROCHI_V2_BLUETOOTH 0x0095
#endif
#ifndef USB_DEVICE_ID_RAZER_NAGA_X
#define USB_DEVICE_ID_RAZER_NAGA_X 0x0096
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_ESSENTIAL_2021
#define USB_DEVICE_ID_RAZER_DEATHADDER_ESSENTIAL_2021 0x0098
#endif
#ifndef USB_DEVICE_ID_RAZER_BASILISK_V3
#define USB_DEVICE_ID_RAZER_BASILISK_V3 0x0099
#endif
#ifndef USB_DEVICE_ID_RAZER_PRO_CLICK_MINI_RECEIVER
#define USB_DEVICE_ID_RAZER_PRO_CLICK_MINI_RECEIVER 0x009A
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_V2_X_HYPERSPEED
#define USB_DEVICE_ID_RAZER_DEATHADDER_V2_X_HYPERSPEED 0x009C
#endif
#ifndef USB_DEVICE_ID_RAZER_VIPER_MINI_SE_WIRED
#define USB_DEVICE_ID_RAZER_VIPER_MINI_SE_WIRED 0x009E
#endif
#ifndef USB_DEVICE_ID_RAZER_VIPER_MINI_SE_WIRELESS
#define USB_DEVICE_ID_RAZER_VIPER_MINI_SE_WIRELESS 0x009F
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_V2_LITE
#define USB_DEVICE_ID_RAZER_DEATHADDER_V2_LITE 0x00A1
#endif
#ifndef USB_DEVICE_ID_RAZER_COBRA
#define USB_DEVICE_ID_RAZER_COBRA 0x00A3
#endif
#ifndef USB_DEVICE_ID_RAZER_VIPER_V2_PRO_WIRED
#define USB_DEVICE_ID_RAZER_VIPER_V2_PRO_WIRED 0x00A5
#endif
#ifndef USB_DEVICE_ID_RAZER_VIPER_V2_PRO_WIRELESS
#define USB_DEVICE_ID_RAZER_VIPER_V2_PRO_WIRELESS 0x00A6
#endif
#ifndef USB_DEVICE_ID_RAZER_NAGA_V2_PRO_WIRED
#define USB_DEVICE_ID_RAZER_NAGA_V2_PRO_WIRED 0x00A7
#endif
#ifndef USB_DEVICE_ID_RAZER_NAGA_V2_PRO_WIRELESS
#define USB_DEVICE_ID_RAZER_NAGA_V2_PRO_WIRELESS 0x00A8
#endif
#ifndef USB_DEVICE_ID_RAZER_BASILISK_V3_PRO_WIRED
#define USB_DEVICE_ID_RAZER_BASILISK_V3_PRO_WIRED 0x00AA
#endif
#ifndef USB_DEVICE_ID_RAZER_BASILISK_V3_PRO_WIRELESS
#define USB_DEVICE_ID_RAZER_BASILISK_V3_PRO_WIRELESS 0x00AB
#endif
#ifndef USB_DEVICE_ID_RAZER_COBRA_PRO_WIRED
#define USB_DEVICE_ID_RAZER_COBRA_PRO_WIRED 0x00AF
#endif
#ifndef USB_DEVICE_ID_RAZER_COBRA_PRO_WIRELESS
#define USB_DEVICE_ID_RAZER_COBRA_PRO_WIRELESS 0x00B0
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_V3
#define USB_DEVICE_ID_RAZER_DEATHADDER_V3 0x00B2
#endif
#ifndef USB_DEVICE_ID_RAZER_HYPERPOLLING_WIRELESS_DONGLE
#define USB_DEVICE_ID_RAZER_HYPERPOLLING_WIRELESS_DONGLE 0x00B3
#endif
#ifndef USB_DEVICE_ID_RAZER_NAGA_V2_HYPERSPEED_RECEIVER
#define USB_DEVICE_ID_RAZER_NAGA_V2_HYPERSPEED_RECEIVER 0x00B4
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_V3_PRO_WIRED
#define USB_DEVICE_ID_RAZER_DEATHADDER_V3_PRO_WIRED 0x00B6
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_V3_PRO_WIRELESS
#define USB_DEVICE_ID_RAZER_DEATHADDER_V3_PRO_WIRELESS 0x00B7
#endif
#ifndef USB_DEVICE_ID_RAZER_VIPER_V3_HYPERSPEED
#define USB_DEVICE_ID_RAZER_VIPER_V3_HYPERSPEED 0x00B8
#endif
#ifndef USB_DEVICE_ID_RAZER_BASILISK_V3_X_HYPERSPEED
#define USB_DEVICE_ID_RAZER_BASILISK_V3_X_HYPERSPEED 0x00B9
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_V4_PRO_WIRED
#define USB_DEVICE_ID_RAZER_DEATHADDER_V4_PRO_WIRED 0x00BE
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_V4_PRO_WIRELESS
#define USB_DEVICE_ID_RAZER_DEATHADDER_V4_PRO_WIRELESS 0x00BF
#endif
#ifndef USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRED
#define USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRED 0x00C0
#endif
#ifndef USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRELESS
#define USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRELESS 0x00C1
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_V3_PRO_WIRED_ALT
#define USB_DEVICE_ID_RAZER_DEATHADDER_V3_PRO_WIRED_ALT 0x00C2
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_V3_PRO_WIRELESS_ALT
#define USB_DEVICE_ID_RAZER_DEATHADDER_V3_PRO_WIRELESS_ALT 0x00C3
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_V3_HYPERSPEED_WIRED
#define USB_DEVICE_ID_RAZER_DEATHADDER_V3_HYPERSPEED_WIRED 0x00C4
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHADDER_V3_HYPERSPEED_WIRELESS
#define USB_DEVICE_ID_RAZER_DEATHADDER_V3_HYPERSPEED_WIRELESS 0x00C5
#endif
#ifndef USB_DEVICE_ID_RAZER_PRO_CLICK_V2_VERTICAL_EDITION_WIRED
#define USB_DEVICE_ID_RAZER_PRO_CLICK_V2_VERTICAL_EDITION_WIRED 0x00C7
#endif
#ifndef USB_DEVICE_ID_RAZER_PRO_CLICK_V2_VERTICAL_EDITION_WIRELESS
#define USB_DEVICE_ID_RAZER_PRO_CLICK_V2_VERTICAL_EDITION_WIRELESS 0x00C8
#endif
#ifndef USB_DEVICE_ID_RAZER_BASILISK_V3_35K
#define USB_DEVICE_ID_RAZER_BASILISK_V3_35K 0x00CB
#endif
#ifndef USB_DEVICE_ID_RAZER_BASILISK_V3_PRO_35K_WIRED
#define USB_DEVICE_ID_RAZER_BASILISK_V3_PRO_35K_WIRED 0x00CC
#endif
#ifndef USB_DEVICE_ID_RAZER_BASILISK_V3_PRO_35K_WIRELESS
#define USB_DEVICE_ID_RAZER_BASILISK_V3_PRO_35K_WIRELESS 0x00CD
#endif
#ifndef USB_DEVICE_ID_RAZER_PRO_CLICK_V2_WIRED
#define USB_DEVICE_ID_RAZER_PRO_CLICK_V2_WIRED 0x00D0
#endif
#ifndef USB_DEVICE_ID_RAZER_PRO_CLICK_V2_WIRELESS
#define USB_DEVICE_ID_RAZER_PRO_CLICK_V2_WIRELESS 0x00D1
#endif
#ifndef USB_DEVICE_ID_RAZER_BASILISK_V3_PRO_35K_PHANTOM_GREEN_EDITION_WIRED
#define USB_DEVICE_ID_RAZER_BASILISK_V3_PRO_35K_PHANTOM_GREEN_EDITION_WIRED 0x00D6
#endif
#ifndef USB_DEVICE_ID_RAZER_BASILISK_V3_PRO_35K_PHANTOM_GREEN_EDITION_WIRELESS
#define USB_DEVICE_ID_RAZER_BASILISK_V3_PRO_35K_PHANTOM_GREEN_EDITION_WIRELESS 0x00D7
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_ULTIMATE_2012
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_ULTIMATE_2012 0x010D
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_STEALTH_EDITION
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_STEALTH_EDITION 0x010E
#endif
#ifndef USB_DEVICE_ID_RAZER_ANANSI
#define USB_DEVICE_ID_RAZER_ANANSI 0x010F
#endif
#ifndef USB_DEVICE_ID_RAZER_NOSTROMO
#define USB_DEVICE_ID_RAZER_NOSTROMO 0x0111
#endif
#ifndef USB_DEVICE_ID_RAZER_ORBWEAVER
#define USB_DEVICE_ID_RAZER_ORBWEAVER 0x0113
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHSTALKER_ESSENTIAL
#define USB_DEVICE_ID_RAZER_DEATHSTALKER_ESSENTIAL 0x0118
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_ULTIMATE_2013
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_ULTIMATE_2013 0x011A
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_STEALTH
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_STEALTH 0x011B
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_TE_2014
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_TE_2014 0x011C
#endif
#ifndef USB_DEVICE_ID_RAZER_TARTARUS
#define USB_DEVICE_ID_RAZER_TARTARUS 0x0201
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHSTALKER_EXPERT
#define USB_DEVICE_ID_RAZER_DEATHSTALKER_EXPERT 0x0202
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_CHROMA
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_CHROMA 0x0203
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHSTALKER_CHROMA
#define USB_DEVICE_ID_RAZER_DEATHSTALKER_CHROMA 0x0204
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_STEALTH
#define USB_DEVICE_ID_RAZER_BLADE_STEALTH 0x0205
#endif
#ifndef USB_DEVICE_ID_RAZER_ORBWEAVER_CHROMA
#define USB_DEVICE_ID_RAZER_ORBWEAVER_CHROMA 0x0207
#endif
#ifndef USB_DEVICE_ID_RAZER_TARTARUS_CHROMA
#define USB_DEVICE_ID_RAZER_TARTARUS_CHROMA 0x0208
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_CHROMA_TE
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_CHROMA_TE 0x0209
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_QHD
#define USB_DEVICE_ID_RAZER_BLADE_QHD 0x020F
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_PRO_LATE_2016
#define USB_DEVICE_ID_RAZER_BLADE_PRO_LATE_2016 0x0210
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_OVERWATCH
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_OVERWATCH 0x0211
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_ULTIMATE_2016
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_ULTIMATE_2016 0x0214
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_X_CHROMA
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_X_CHROMA 0x0216
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_X_ULTIMATE
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_X_ULTIMATE 0x0217
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_X_CHROMA_TE
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_X_CHROMA_TE 0x021A
#endif
#ifndef USB_DEVICE_ID_RAZER_ORNATA_CHROMA
#define USB_DEVICE_ID_RAZER_ORNATA_CHROMA 0x021E
#endif
#ifndef USB_DEVICE_ID_RAZER_ORNATA
#define USB_DEVICE_ID_RAZER_ORNATA 0x021F
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_STEALTH_LATE_2016
#define USB_DEVICE_ID_RAZER_BLADE_STEALTH_LATE_2016 0x0220
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_CHROMA_V2
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_CHROMA_V2 0x0221
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_LATE_2016
#define USB_DEVICE_ID_RAZER_BLADE_LATE_2016 0x0224
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_PRO_2017
#define USB_DEVICE_ID_RAZER_BLADE_PRO_2017 0x0225
#endif
#ifndef USB_DEVICE_ID_RAZER_HUNTSMAN_ELITE
#define USB_DEVICE_ID_RAZER_HUNTSMAN_ELITE 0x0226
#endif
#ifndef USB_DEVICE_ID_RAZER_HUNTSMAN
#define USB_DEVICE_ID_RAZER_HUNTSMAN 0x0227
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_ELITE
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_ELITE 0x0228
#endif
#ifndef USB_DEVICE_ID_RAZER_CYNOSA_CHROMA
#define USB_DEVICE_ID_RAZER_CYNOSA_CHROMA 0x022A
#endif
#ifndef USB_DEVICE_ID_RAZER_TARTARUS_V2
#define USB_DEVICE_ID_RAZER_TARTARUS_V2 0x022B
#endif
#ifndef USB_DEVICE_ID_RAZER_CYNOSA_CHROMA_PRO
#define USB_DEVICE_ID_RAZER_CYNOSA_CHROMA_PRO 0x022C
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_STEALTH_MID_2017
#define USB_DEVICE_ID_RAZER_BLADE_STEALTH_MID_2017 0x022D
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_PRO_2017_FULLHD
#define USB_DEVICE_ID_RAZER_BLADE_PRO_2017_FULLHD 0x022F
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_STEALTH_LATE_2017
#define USB_DEVICE_ID_RAZER_BLADE_STEALTH_LATE_2017 0x0232
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_2018
#define USB_DEVICE_ID_RAZER_BLADE_2018 0x0233
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_PRO_2019
#define USB_DEVICE_ID_RAZER_BLADE_PRO_2019 0x0234
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_LITE
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_LITE 0x0235
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_ESSENTIAL
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_ESSENTIAL 0x0237
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_STEALTH_2019
#define USB_DEVICE_ID_RAZER_BLADE_STEALTH_2019 0x0239
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_2019_ADV
#define USB_DEVICE_ID_RAZER_BLADE_2019_ADV 0x023A
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_2018_BASE
#define USB_DEVICE_ID_RAZER_BLADE_2018_BASE 0x023B
#endif
#ifndef USB_DEVICE_ID_RAZER_CYNOSA_LITE
#define USB_DEVICE_ID_RAZER_CYNOSA_LITE 0x023F
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_2018_MERCURY
#define USB_DEVICE_ID_RAZER_BLADE_2018_MERCURY 0x0240
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_2019
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_2019 0x0241
#endif
#ifndef USB_DEVICE_ID_RAZER_HUNTSMAN_TE
#define USB_DEVICE_ID_RAZER_HUNTSMAN_TE 0x0243
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_MID_2019_MERCURY
#define USB_DEVICE_ID_RAZER_BLADE_MID_2019_MERCURY 0x0245
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_2019_BASE
#define USB_DEVICE_ID_RAZER_BLADE_2019_BASE 0x0246
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_STEALTH_LATE_2019
#define USB_DEVICE_ID_RAZER_BLADE_STEALTH_LATE_2019 0x024A
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_ADV_LATE_2019
#define USB_DEVICE_ID_RAZER_BLADE_ADV_LATE_2019 0x024B
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_PRO_LATE_2019
#define USB_DEVICE_ID_RAZER_BLADE_PRO_LATE_2019 0x024C
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_STUDIO_EDITION_2019
#define USB_DEVICE_ID_RAZER_BLADE_STUDIO_EDITION_2019 0x024D
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_V3
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_V3 0x024E
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_STEALTH_EARLY_2020
#define USB_DEVICE_ID_RAZER_BLADE_STEALTH_EARLY_2020 0x0252
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_15_ADV_2020
#define USB_DEVICE_ID_RAZER_BLADE_15_ADV_2020 0x0253
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_EARLY_2020_BASE
#define USB_DEVICE_ID_RAZER_BLADE_EARLY_2020_BASE 0x0255
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_PRO_EARLY_2020
#define USB_DEVICE_ID_RAZER_BLADE_PRO_EARLY_2020 0x0256
#endif
#ifndef USB_DEVICE_ID_RAZER_HUNTSMAN_MINI
#define USB_DEVICE_ID_RAZER_HUNTSMAN_MINI 0x0257
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_V3_MINI_HYPERSPEED_WIRED
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_V3_MINI_HYPERSPEED_WIRED 0x0258
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_STEALTH_LATE_2020
#define USB_DEVICE_ID_RAZER_BLADE_STEALTH_LATE_2020 0x0259
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_V3_PRO_WIRED
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_V3_PRO_WIRED 0x025A
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_V3_PRO_WIRELESS
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_V3_PRO_WIRELESS 0x025C
#endif
#ifndef USB_DEVICE_ID_RAZER_ORNATA_V2
#define USB_DEVICE_ID_RAZER_ORNATA_V2 0x025D
#endif
#ifndef USB_DEVICE_ID_RAZER_CYNOSA_V2
#define USB_DEVICE_ID_RAZER_CYNOSA_V2 0x025E
#endif
#ifndef USB_DEVICE_ID_RAZER_HUNTSMAN_V2_ANALOG
#define USB_DEVICE_ID_RAZER_HUNTSMAN_V2_ANALOG 0x0266
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_LATE_2020_BASE
#define USB_DEVICE_ID_RAZER_BLADE_LATE_2020_BASE 0x0268
#endif
#ifndef USB_DEVICE_ID_RAZER_HUNTSMAN_MINI_JP
#define USB_DEVICE_ID_RAZER_HUNTSMAN_MINI_JP 0x0269
#endif
#ifndef USB_DEVICE_ID_RAZER_BOOK_2020
#define USB_DEVICE_ID_RAZER_BOOK_2020 0x026A
#endif
#ifndef USB_DEVICE_ID_RAZER_HUNTSMAN_V2_TENKEYLESS
#define USB_DEVICE_ID_RAZER_HUNTSMAN_V2_TENKEYLESS 0x026B
#endif
#ifndef USB_DEVICE_ID_RAZER_HUNTSMAN_V2
#define USB_DEVICE_ID_RAZER_HUNTSMAN_V2 0x026C
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_15_ADV_EARLY_2021
#define USB_DEVICE_ID_RAZER_BLADE_15_ADV_EARLY_2021 0x026D
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_17_PRO_EARLY_2021
#define USB_DEVICE_ID_RAZER_BLADE_17_PRO_EARLY_2021 0x026E
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_15_BASE_EARLY_2021
#define USB_DEVICE_ID_RAZER_BLADE_15_BASE_EARLY_2021 0x026F
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_14_2021
#define USB_DEVICE_ID_RAZER_BLADE_14_2021 0x0270
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_V3_MINI_HYPERSPEED_WIRELESS
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_V3_MINI_HYPERSPEED_WIRELESS 0x0271
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_15_ADV_MID_2021
#define USB_DEVICE_ID_RAZER_BLADE_15_ADV_MID_2021 0x0276
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_17_PRO_MID_2021
#define USB_DEVICE_ID_RAZER_BLADE_17_PRO_MID_2021 0x0279
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_15_BASE_2022
#define USB_DEVICE_ID_RAZER_BLADE_15_BASE_2022 0x027A
#endif
#ifndef USB_DEVICE_ID_RAZER_HUNTSMAN_MINI_ANALOG
#define USB_DEVICE_ID_RAZER_HUNTSMAN_MINI_ANALOG 0x0282
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_V4
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_V4 0x0287
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_15_ADV_EARLY_2022
#define USB_DEVICE_ID_RAZER_BLADE_15_ADV_EARLY_2022 0x028A
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_17_2022
#define USB_DEVICE_ID_RAZER_BLADE_17_2022 0x028B
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_14_2022
#define USB_DEVICE_ID_RAZER_BLADE_14_2022 0x028C
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_V4_PRO
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_V4_PRO 0x028D
#endif
#ifndef USB_DEVICE_ID_RAZER_ORNATA_V3_ALT
#define USB_DEVICE_ID_RAZER_ORNATA_V3_ALT 0x028F
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHSTALKER_V2_PRO_WIRELESS
#define USB_DEVICE_ID_RAZER_DEATHSTALKER_V2_PRO_WIRELESS 0x0290
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHSTALKER_V2_PRO_WIRED
#define USB_DEVICE_ID_RAZER_DEATHSTALKER_V2_PRO_WIRED 0x0292
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_V4_X
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_V4_X 0x0293
#endif
#ifndef USB_DEVICE_ID_RAZER_ORNATA_V3_X
#define USB_DEVICE_ID_RAZER_ORNATA_V3_X 0x0294
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHSTALKER_V2
#define USB_DEVICE_ID_RAZER_DEATHSTALKER_V2 0x0295
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHSTALKER_V2_PRO_TKL_WIRELESS
#define USB_DEVICE_ID_RAZER_DEATHSTALKER_V2_PRO_TKL_WIRELESS 0x0296
#endif
#ifndef USB_DEVICE_ID_RAZER_DEATHSTALKER_V2_PRO_TKL_WIRED
#define USB_DEVICE_ID_RAZER_DEATHSTALKER_V2_PRO_TKL_WIRED 0x0298
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_14_2023
#define USB_DEVICE_ID_RAZER_BLADE_14_2023 0x029D
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_15_2023
#define USB_DEVICE_ID_RAZER_BLADE_15_2023 0x029E
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_16_2023
#define USB_DEVICE_ID_RAZER_BLADE_16_2023 0x029F
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_18_2023
#define USB_DEVICE_ID_RAZER_BLADE_18_2023 0x02A0
#endif
#ifndef USB_DEVICE_ID_RAZER_ORNATA_V3
#define USB_DEVICE_ID_RAZER_ORNATA_V3 0x02A1
#endif
#ifndef USB_DEVICE_ID_RAZER_ORNATA_V3_X_ALT
#define USB_DEVICE_ID_RAZER_ORNATA_V3_X_ALT 0x02A2
#endif
#ifndef USB_DEVICE_ID_RAZER_ORNATA_V3_TENKEYLESS
#define USB_DEVICE_ID_RAZER_ORNATA_V3_TENKEYLESS 0x02A3
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_V4_75PCT
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_V4_75PCT 0x02A5
#endif
#ifndef USB_DEVICE_ID_RAZER_HUNTSMAN_V3_PRO
#define USB_DEVICE_ID_RAZER_HUNTSMAN_V3_PRO 0x02A6
#endif
#ifndef USB_DEVICE_ID_RAZER_HUNTSMAN_V3_PRO_TKL
#define USB_DEVICE_ID_RAZER_HUNTSMAN_V3_PRO_TKL 0x02A7
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_14_2024
#define USB_DEVICE_ID_RAZER_BLADE_14_2024 0x02B6
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_18_2024
#define USB_DEVICE_ID_RAZER_BLADE_18_2024 0x02B8
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_V4_MINI_HYPERSPEED_WIRED
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_V4_MINI_HYPERSPEED_WIRED 0x02B9
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_V4_MINI_HYPERSPEED_WIRELESS
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_V4_MINI_HYPERSPEED_WIRELESS 0x02BA
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_14_2025
#define USB_DEVICE_ID_RAZER_BLADE_14_2025 0x02C5
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_16_2025
#define USB_DEVICE_ID_RAZER_BLADE_16_2025 0x02C6
#endif
#ifndef USB_DEVICE_ID_RAZER_BLADE_18_2025
#define USB_DEVICE_ID_RAZER_BLADE_18_2025 0x02C7
#endif
#ifndef USB_DEVICE_ID_RAZER_BLACKWIDOW_V3_TK
#define USB_DEVICE_ID_RAZER_BLACKWIDOW_V3_TK 0x0A24
#endif
#ifndef USB_DEVICE_ID_RAZER_KRAKEN_CLASSIC
#define USB_DEVICE_ID_RAZER_KRAKEN_CLASSIC 0x0501
#endif
#ifndef USB_DEVICE_ID_RAZER_KRAKEN
#define USB_DEVICE_ID_RAZER_KRAKEN 0x0504
#endif
#ifndef USB_DEVICE_ID_RAZER_KRAKEN_CLASSIC_ALT
#define USB_DEVICE_ID_RAZER_KRAKEN_CLASSIC_ALT 0x0506
#endif
#ifndef USB_DEVICE_ID_RAZER_KRAKEN_V2
#define USB_DEVICE_ID_RAZER_KRAKEN_V2 0x0510
#endif
#ifndef USB_DEVICE_ID_RAZER_KRAKEN_ULTIMATE
#define USB_DEVICE_ID_RAZER_KRAKEN_ULTIMATE 0x0527
#endif
#ifndef USB_DEVICE_ID_RAZER_KRAKEN_KITTY_V2
#define USB_DEVICE_ID_RAZER_KRAKEN_KITTY_V2 0x0560
#endif
#ifndef USB_DEVICE_ID_RAZER_FIREFLY_HYPERFLUX
#define USB_DEVICE_ID_RAZER_FIREFLY_HYPERFLUX 0x0068
#endif
#ifndef USB_DEVICE_ID_RAZER_MOUSE_DOCK
#define USB_DEVICE_ID_RAZER_MOUSE_DOCK 0x007E
#endif
#ifndef USB_DEVICE_ID_RAZER_CORE
#define USB_DEVICE_ID_RAZER_CORE 0x0215
#endif
#ifndef USB_DEVICE_ID_RAZER_NOMMO_CHROMA
#define USB_DEVICE_ID_RAZER_NOMMO_CHROMA 0x0517
#endif
#ifndef USB_DEVICE_ID_RAZER_NOMMO_PRO
#define USB_DEVICE_ID_RAZER_NOMMO_PRO 0x0518
#endif
#ifndef USB_DEVICE_ID_RAZER_FIREFLY
#define USB_DEVICE_ID_RAZER_FIREFLY 0x0C00
#endif
#ifndef USB_DEVICE_ID_RAZER_GOLIATHUS_CHROMA
#define USB_DEVICE_ID_RAZER_GOLIATHUS_CHROMA 0x0C01
#endif
#ifndef USB_DEVICE_ID_RAZER_GOLIATHUS_CHROMA_EXTENDED
#define USB_DEVICE_ID_RAZER_GOLIATHUS_CHROMA_EXTENDED 0x0C02
#endif
#ifndef USB_DEVICE_ID_RAZER_FIREFLY_V2
#define USB_DEVICE_ID_RAZER_FIREFLY_V2 0x0C04
#endif
#ifndef USB_DEVICE_ID_RAZER_STRIDER_CHROMA
#define USB_DEVICE_ID_RAZER_STRIDER_CHROMA 0x0C05
#endif
#ifndef USB_DEVICE_ID_RAZER_GOLIATHUS_CHROMA_3XL
#define USB_DEVICE_ID_RAZER_GOLIATHUS_CHROMA_3XL 0x0C06
#endif
#ifndef USB_DEVICE_ID_RAZER_FIREFLY_V2_PRO
#define USB_DEVICE_ID_RAZER_FIREFLY_V2_PRO 0x0C08
#endif
#ifndef USB_DEVICE_ID_RAZER_CHROMA_MUG
#define USB_DEVICE_ID_RAZER_CHROMA_MUG 0x0F07
#endif
#ifndef USB_DEVICE_ID_RAZER_CHROMA_BASE
#define USB_DEVICE_ID_RAZER_CHROMA_BASE 0x0F08
#endif
#ifndef USB_DEVICE_ID_RAZER_CHROMA_HDK
#define USB_DEVICE_ID_RAZER_CHROMA_HDK 0x0F09
#endif
#ifndef USB_DEVICE_ID_RAZER_LAPTOP_STAND_CHROMA
#define USB_DEVICE_ID_RAZER_LAPTOP_STAND_CHROMA 0x0F0D
#endif
#ifndef USB_DEVICE_ID_RAZER_RAPTOR_27
#define USB_DEVICE_ID_RAZER_RAPTOR_27 0x0F12
#endif
#ifndef USB_DEVICE_ID_RAZER_TOMAHAWK_ATX
#define USB_DEVICE_ID_RAZER_TOMAHAWK_ATX 0x0F17
#endif
#ifndef USB_DEVICE_ID_RAZER_KRAKEN_KITTY_EDITION
#define USB_DEVICE_ID_RAZER_KRAKEN_KITTY_EDITION 0x0F19
#endif
#ifndef USB_DEVICE_ID_RAZER_CORE_X_CHROMA
#define USB_DEVICE_ID_RAZER_CORE_X_CHROMA 0x0F1A
#endif
#ifndef USB_DEVICE_ID_RAZER_MOUSE_BUNGEE_V3_CHROMA
#define USB_DEVICE_ID_RAZER_MOUSE_BUNGEE_V3_CHROMA 0x0F1D
#endif
#ifndef USB_DEVICE_ID_RAZER_CHROMA_ADDRESSABLE_RGB_CONTROLLER
#define USB_DEVICE_ID_RAZER_CHROMA_ADDRESSABLE_RGB_CONTROLLER 0x0F1F
#endif
#ifndef USB_DEVICE_ID_RAZER_BASE_STATION_V2_CHROMA
#define USB_DEVICE_ID_RAZER_BASE_STATION_V2_CHROMA 0x0F20
#endif
#ifndef USB_DEVICE_ID_RAZER_THUNDERBOLT_4_DOCK_CHROMA
#define USB_DEVICE_ID_RAZER_THUNDERBOLT_4_DOCK_CHROMA 0x0F21
#endif
#ifndef USB_DEVICE_ID_RAZER_CHARGING_PAD_CHROMA
#define USB_DEVICE_ID_RAZER_CHARGING_PAD_CHROMA 0x0F26
#endif
#ifndef USB_DEVICE_ID_RAZER_LAPTOP_STAND_CHROMA_V2
#define USB_DEVICE_ID_RAZER_LAPTOP_STAND_CHROMA_V2 0x0F2B
#endif

#include <map>

enum class RazerDeviceType { Mouse, Keyboard, Headset, Accessory, Unknown };

inline RazerDeviceType GetRazerDeviceType(int pid) {
    switch(pid) {
    case USB_DEVICE_ID_RAZER_OROCHI_2011: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_NAGA: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_3_5G: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_NAGA_EPIC: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_ABYSSUS_1800: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_MAMBA_2012_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_MAMBA_2012_WIRELESS: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_3_5G_BLACK: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_NAGA_2012: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_IMPERATOR: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_OUROBOROS: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_TAIPAN: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_NAGA_HEX_RED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_2013: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_1800: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_OROCHI_2013: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_NAGA_EPIC_CHROMA: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_NAGA_EPIC_CHROMA_DOCK: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_NAGA_2014: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_NAGA_HEX: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_ABYSSUS: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_CHROMA: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_MAMBA_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_MAMBA_WIRELESS: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_MAMBA_TE_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_OROCHI_CHROMA: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DIAMONDBACK_CHROMA: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_2000: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_NAGA_HEX_V2: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_NAGA_CHROMA: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_3500: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_LANCEHEAD_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_LANCEHEAD_WIRELESS: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_ABYSSUS_V2: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_ELITE: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_ABYSSUS_2000: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_LANCEHEAD_TE_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_ATHERIS_RECEIVER: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_BASILISK: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_BASILISK_ESSENTIAL: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_NAGA_TRINITY: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_ABYSSUS_ELITE_DVA_EDITION: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_ABYSSUS_ESSENTIAL: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_MAMBA_ELITE: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_ESSENTIAL: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_LANCEHEAD_WIRELESS_RECEIVER: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_LANCEHEAD_WIRELESS_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_ESSENTIAL_WHITE_EDITION: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_MAMBA_WIRELESS_RECEIVER: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_MAMBA_WIRELESS_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_PRO_CLICK_RECEIVER: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_VIPER: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_VIPER_ULTIMATE_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_VIPER_ULTIMATE_WIRELESS: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_V2_PRO_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_V2_PRO_WIRELESS: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_PRO_CLICK_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_BASILISK_X_HYPERSPEED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_V2: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_BASILISK_V2: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_BASILISK_ULTIMATE_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_BASILISK_ULTIMATE_RECEIVER: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_VIPER_MINI: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_V2_MINI: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_NAGA_LEFT_HANDED_2020: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_NAGA_PRO_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_NAGA_PRO_WIRELESS: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_VIPER_8K: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_OROCHI_V2_RECEIVER: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_OROCHI_V2_BLUETOOTH: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_NAGA_X: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_ESSENTIAL_2021: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_BASILISK_V3: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_PRO_CLICK_MINI_RECEIVER: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_V2_X_HYPERSPEED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_VIPER_MINI_SE_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_VIPER_MINI_SE_WIRELESS: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_V2_LITE: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_COBRA: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_VIPER_V2_PRO_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_VIPER_V2_PRO_WIRELESS: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_NAGA_V2_PRO_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_NAGA_V2_PRO_WIRELESS: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_BASILISK_V3_PRO_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_BASILISK_V3_PRO_WIRELESS: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_COBRA_PRO_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_COBRA_PRO_WIRELESS: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_V3: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_HYPERPOLLING_WIRELESS_DONGLE: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_NAGA_V2_HYPERSPEED_RECEIVER: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_V3_PRO_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_V3_PRO_WIRELESS: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_VIPER_V3_HYPERSPEED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_BASILISK_V3_X_HYPERSPEED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_V4_PRO_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_V4_PRO_WIRELESS: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_VIPER_V3_PRO_WIRELESS: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_V3_PRO_WIRED_ALT: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_V3_PRO_WIRELESS_ALT: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_V3_HYPERSPEED_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_DEATHADDER_V3_HYPERSPEED_WIRELESS: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_PRO_CLICK_V2_VERTICAL_EDITION_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_PRO_CLICK_V2_VERTICAL_EDITION_WIRELESS: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_BASILISK_V3_35K: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_BASILISK_V3_PRO_35K_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_BASILISK_V3_PRO_35K_WIRELESS: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_PRO_CLICK_V2_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_PRO_CLICK_V2_WIRELESS: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_BASILISK_V3_PRO_35K_PHANTOM_GREEN_EDITION_WIRED: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_BASILISK_V3_PRO_35K_PHANTOM_GREEN_EDITION_WIRELESS: return RazerDeviceType::Mouse;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_ULTIMATE_2012: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_STEALTH_EDITION: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_ANANSI: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_NOSTROMO: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_ORBWEAVER: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_DEATHSTALKER_ESSENTIAL: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_ULTIMATE_2013: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_STEALTH: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_TE_2014: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_TARTARUS: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_DEATHSTALKER_EXPERT: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_CHROMA: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_DEATHSTALKER_CHROMA: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_STEALTH: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_ORBWEAVER_CHROMA: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_TARTARUS_CHROMA: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_CHROMA_TE: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_QHD: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_PRO_LATE_2016: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_OVERWATCH: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_ULTIMATE_2016: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_X_CHROMA: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_X_ULTIMATE: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_X_CHROMA_TE: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_ORNATA_CHROMA: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_ORNATA: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_STEALTH_LATE_2016: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_CHROMA_V2: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_LATE_2016: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_PRO_2017: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_HUNTSMAN_ELITE: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_HUNTSMAN: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_ELITE: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_CYNOSA_CHROMA: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_TARTARUS_V2: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_CYNOSA_CHROMA_PRO: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_STEALTH_MID_2017: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_PRO_2017_FULLHD: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_STEALTH_LATE_2017: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_2018: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_PRO_2019: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_LITE: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_ESSENTIAL: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_STEALTH_2019: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_2019_ADV: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_2018_BASE: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_CYNOSA_LITE: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_2018_MERCURY: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_2019: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_HUNTSMAN_TE: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_MID_2019_MERCURY: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_2019_BASE: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_STEALTH_LATE_2019: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_ADV_LATE_2019: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_PRO_LATE_2019: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_STUDIO_EDITION_2019: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_V3: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_STEALTH_EARLY_2020: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_15_ADV_2020: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_EARLY_2020_BASE: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_PRO_EARLY_2020: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_HUNTSMAN_MINI: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_V3_MINI_HYPERSPEED_WIRED: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_STEALTH_LATE_2020: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_V3_PRO_WIRED: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_V3_PRO_WIRELESS: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_ORNATA_V2: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_CYNOSA_V2: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_HUNTSMAN_V2_ANALOG: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_LATE_2020_BASE: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_HUNTSMAN_MINI_JP: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BOOK_2020: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_HUNTSMAN_V2_TENKEYLESS: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_HUNTSMAN_V2: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_15_ADV_EARLY_2021: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_17_PRO_EARLY_2021: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_15_BASE_EARLY_2021: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_14_2021: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_V3_MINI_HYPERSPEED_WIRELESS: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_15_ADV_MID_2021: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_17_PRO_MID_2021: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_15_BASE_2022: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_HUNTSMAN_MINI_ANALOG: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_V4: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_15_ADV_EARLY_2022: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_17_2022: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_14_2022: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_V4_PRO: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_ORNATA_V3_ALT: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_DEATHSTALKER_V2_PRO_WIRELESS: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_DEATHSTALKER_V2_PRO_WIRED: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_V4_X: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_ORNATA_V3_X: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_DEATHSTALKER_V2: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_DEATHSTALKER_V2_PRO_TKL_WIRELESS: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_DEATHSTALKER_V2_PRO_TKL_WIRED: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_14_2023: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_15_2023: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_16_2023: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_18_2023: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_ORNATA_V3: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_ORNATA_V3_X_ALT: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_ORNATA_V3_TENKEYLESS: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_V4_75PCT: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_HUNTSMAN_V3_PRO: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_HUNTSMAN_V3_PRO_TKL: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_14_2024: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_18_2024: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_V4_MINI_HYPERSPEED_WIRED: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_V4_MINI_HYPERSPEED_WIRELESS: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_14_2025: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_16_2025: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLADE_18_2025: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_BLACKWIDOW_V3_TK: return RazerDeviceType::Keyboard;
    case USB_DEVICE_ID_RAZER_KRAKEN_CLASSIC: return RazerDeviceType::Headset;
    case USB_DEVICE_ID_RAZER_KRAKEN: return RazerDeviceType::Headset;
    case USB_DEVICE_ID_RAZER_KRAKEN_CLASSIC_ALT: return RazerDeviceType::Headset;
    case USB_DEVICE_ID_RAZER_KRAKEN_V2: return RazerDeviceType::Headset;
    case USB_DEVICE_ID_RAZER_KRAKEN_ULTIMATE: return RazerDeviceType::Headset;
    case USB_DEVICE_ID_RAZER_KRAKEN_KITTY_V2: return RazerDeviceType::Headset;
    case USB_DEVICE_ID_RAZER_FIREFLY_HYPERFLUX: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_MOUSE_DOCK: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_CORE: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_NOMMO_CHROMA: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_NOMMO_PRO: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_FIREFLY: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_GOLIATHUS_CHROMA: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_GOLIATHUS_CHROMA_EXTENDED: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_FIREFLY_V2: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_STRIDER_CHROMA: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_GOLIATHUS_CHROMA_3XL: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_FIREFLY_V2_PRO: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_CHROMA_MUG: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_CHROMA_BASE: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_CHROMA_HDK: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_LAPTOP_STAND_CHROMA: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_RAPTOR_27: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_TOMAHAWK_ATX: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_KRAKEN_KITTY_EDITION: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_CORE_X_CHROMA: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_MOUSE_BUNGEE_V3_CHROMA: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_CHROMA_ADDRESSABLE_RGB_CONTROLLER: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_BASE_STATION_V2_CHROMA: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_THUNDERBOLT_4_DOCK_CHROMA: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_CHARGING_PAD_CHROMA: return RazerDeviceType::Accessory;
    case USB_DEVICE_ID_RAZER_LAPTOP_STAND_CHROMA_V2: return RazerDeviceType::Accessory;
    default: return RazerDeviceType::Unknown;
    }
}
